version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/raw
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas:
  AfterInstall:
    - location: scripts/install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/service-run.sh
      runas: root
timeout: 60